### ISSUE TITLE
Missing Rupee symbol on main Webpage

### ISSUE THREAD

**Issue by dsrikara** [goobes/box#1]
Firefox Browser 58.0.2(32 Bit) used in a Windows Vista system. Problem exists in Chrome and IE also.

**Comment by arunk** [comment]
Found the same issue on the computer at the store. Fixed it by downloading and applying this patch - https://support.microsoft.com/en-in/help/2496898/an-update-to-support-the-new-currency-symbol-for-the-indian-rupee-in-w

**Comment by dsrikara** [comment]
So, the system needs to be updated with this patch?

**Comment by arunk** [comment]
Yes this patch fixes the missing rupee symbol. The symbol is displayed correctly now on the store computer.
